/*----------------------------------------------------------------------
 * This file is generated by mk_parser.py.
 *----------------------------------------------------------------------*/
#include <assert.h>
#include <stdint.h>
#include <stdio.h>
#include "cparser.h"
#include "cparser_priv.h"
#include "cparser_token.h"
#include "cparser_tree.h"

cparser_result_t
cparser_glue_clear_screen (cparser_t *parser)
{
    cparser_cmd_clear_screen(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_lock (cparser_t *parser)
{
    cparser_cmd_lock(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_logout (cparser_t *parser)
{
    cparser_cmd_logout(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_enable_privileged_mode (cparser_t *parser)
{
    cparser_cmd_enable_privileged_mode(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_run_script_filename (cparser_t *parser)
{
    char *filename_val;
    char **filename_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_string(&parser->tokens[1], &filename_val);
    assert(CPARSER_OK == rc);
    filename_ptr = &filename_val;
    cparser_cmd_run_script_filename(&parser->context,
        filename_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_show_users (cparser_t *parser)
{
    cparser_cmd_show_users(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_show_interface (cparser_t *parser)
{
    cparser_cmd_show_interface(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_configure_terminal (cparser_t *parser)
{
    cparser_cmd_configure_terminal(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_config_set_hostname_hostname (cparser_t *parser)
{
    char *hostname_val;
    char **hostname_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_string(&parser->tokens[2], &hostname_val);
    assert(CPARSER_OK == rc);
    hostname_ptr = &hostname_val;
    cparser_cmd_config_set_hostname_hostname(&parser->context,
        hostname_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_config_user_add_username_password_level (cparser_t *parser)
{
    char *username_val;
    char **username_ptr = NULL;
    char *password_val;
    char **password_ptr = NULL;
    int32_t level_val;
    int32_t *level_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_string(&parser->tokens[2], &username_val);
    assert(CPARSER_OK == rc);
    username_ptr = &username_val;
    rc = cparser_get_string(&parser->tokens[3], &password_val);
    assert(CPARSER_OK == rc);
    password_ptr = &password_val;
    rc = cparser_get_int(&parser->tokens[4], &level_val);
    assert(CPARSER_OK == rc);
    level_ptr = &level_val;
    cparser_cmd_config_user_add_username_password_level(&parser->context,
        username_ptr,
        password_ptr,
        level_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_config_user_del_username (cparser_t *parser)
{
    char *username_val;
    char **username_ptr = NULL;
    cparser_result_t rc;

    rc = cparser_get_string(&parser->tokens[2], &username_val);
    assert(CPARSER_OK == rc);
    username_ptr = &username_val;
    cparser_cmd_config_user_del_username(&parser->context,
        username_ptr);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_config_end (cparser_t *parser)
{
    cparser_cmd_config_end(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_config_exit (cparser_t *parser)
{
    cparser_cmd_config_exit(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_end (cparser_t *parser)
{
    cparser_cmd_end(&parser->context);
    return CPARSER_OK;
}

cparser_result_t
cparser_glue_exit (cparser_t *parser)
{
    cparser_cmd_exit(&parser->context);
    return CPARSER_OK;
}

cparser_node_t cparser_node_exit_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_exit,
    "Exit from the current mode",
    NULL,
    NULL
};

cparser_node_t cparser_node_exit = {
    CPARSER_NODE_KEYWORD,
    0,
    "exit",
    NULL,
    NULL,
    &cparser_node_exit_eol
};

cparser_node_t cparser_node_end_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_end,
    "Changes to the exec mode",
    NULL,
    NULL
};

cparser_node_t cparser_node_end = {
    CPARSER_NODE_KEYWORD,
    0,
    "end",
    NULL,
    &cparser_node_exit,
    &cparser_node_end_eol
};

cparser_node_t cparser_node_configure_terminal_root_exit_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_config_exit,
    "Exit from the current mode",
    NULL,
    NULL
};

cparser_node_t cparser_node_configure_terminal_root_exit = {
    CPARSER_NODE_KEYWORD,
    0,
    "exit",
    NULL,
    NULL,
    &cparser_node_configure_terminal_root_exit_eol
};

cparser_node_t cparser_node_configure_terminal_root_end_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_config_end,
    "Changes to the exec mode",
    NULL,
    NULL
};

cparser_node_t cparser_node_configure_terminal_root_end = {
    CPARSER_NODE_KEYWORD,
    0,
    "end",
    NULL,
    &cparser_node_configure_terminal_root_exit,
    &cparser_node_configure_terminal_root_end_eol
};

cparser_node_t cparser_node_configure_terminal_root_user_del_username_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_config_user_del_username,
    "Deletes user",
    NULL,
    NULL
};

cparser_node_t cparser_node_configure_terminal_root_user_del_username = {
    CPARSER_NODE_STRING,
    0,
    "<STRING:username>",
    NULL,
    NULL,
    &cparser_node_configure_terminal_root_user_del_username_eol
};

cparser_node_t cparser_node_configure_terminal_root_user_del = {
    CPARSER_NODE_KEYWORD,
    0,
    "del",
    NULL,
    NULL,
    &cparser_node_configure_terminal_root_user_del_username
};

cparser_node_t cparser_node_configure_terminal_root_user_add_username_password_level_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_config_user_add_username_password_level,
    "Add new user ",
    NULL,
    NULL
};

cparser_node_t cparser_node_configure_terminal_root_user_add_username_password_level = {
    CPARSER_NODE_INT,
    0,
    "<INT:level>",
    NULL,
    NULL,
    &cparser_node_configure_terminal_root_user_add_username_password_level_eol
};

cparser_node_t cparser_node_configure_terminal_root_user_add_username_password = {
    CPARSER_NODE_STRING,
    0,
    "<STRING:password>",
    NULL,
    NULL,
    &cparser_node_configure_terminal_root_user_add_username_password_level
};

cparser_node_t cparser_node_configure_terminal_root_user_add_username = {
    CPARSER_NODE_STRING,
    0,
    "<STRING:username>",
    NULL,
    NULL,
    &cparser_node_configure_terminal_root_user_add_username_password
};

cparser_node_t cparser_node_configure_terminal_root_user_add = {
    CPARSER_NODE_KEYWORD,
    0,
    "add",
    NULL,
    &cparser_node_configure_terminal_root_user_del,
    &cparser_node_configure_terminal_root_user_add_username
};

cparser_node_t cparser_node_configure_terminal_root_user = {
    CPARSER_NODE_KEYWORD,
    0,
    "user",
    NULL,
    &cparser_node_configure_terminal_root_end,
    &cparser_node_configure_terminal_root_user_add
};

cparser_node_t cparser_node_configure_terminal_root_set_hostname_hostname_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_config_set_hostname_hostname,
    "Sets hostname",
    NULL,
    NULL
};

cparser_node_t cparser_node_configure_terminal_root_set_hostname_hostname = {
    CPARSER_NODE_STRING,
    0,
    "<STRING:hostname>",
    NULL,
    NULL,
    &cparser_node_configure_terminal_root_set_hostname_hostname_eol
};

cparser_node_t cparser_node_configure_terminal_root_set_hostname = {
    CPARSER_NODE_KEYWORD,
    0,
    "hostname",
    NULL,
    NULL,
    &cparser_node_configure_terminal_root_set_hostname_hostname
};

cparser_node_t cparser_node_configure_terminal_root_set = {
    CPARSER_NODE_KEYWORD,
    0,
    "set",
    NULL,
    &cparser_node_configure_terminal_root_user,
    &cparser_node_configure_terminal_root_set_hostname
};

cparser_node_t cparser_node_configure_terminal_root = {
    CPARSER_NODE_ROOT,
    0,
    NULL,
    "Root of submode config",
    NULL,
    &cparser_node_configure_terminal_root_set
};

cparser_node_t cparser_node_configure_terminal_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_configure_terminal,
    "configuration mode",
    NULL,
    &cparser_node_configure_terminal_root
};

cparser_node_t cparser_node_configure_terminal = {
    CPARSER_NODE_KEYWORD,
    0,
    "terminal",
    NULL,
    NULL,
    &cparser_node_configure_terminal_eol
};

cparser_node_t cparser_node_configure = {
    CPARSER_NODE_KEYWORD,
    0,
    "configure",
    NULL,
    &cparser_node_end,
    &cparser_node_configure_terminal
};

cparser_node_t cparser_node_show_interface_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_show_interface,
    "Displays interface",
    NULL,
    NULL
};

cparser_node_t cparser_node_show_interface = {
    CPARSER_NODE_KEYWORD,
    0,
    "interface",
    NULL,
    NULL,
    &cparser_node_show_interface_eol
};

cparser_node_t cparser_node_show_users_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_show_users,
    "Displays user info",
    NULL,
    NULL
};

cparser_node_t cparser_node_show_users = {
    CPARSER_NODE_KEYWORD,
    0,
    "users",
    NULL,
    &cparser_node_show_interface,
    &cparser_node_show_users_eol
};

cparser_node_t cparser_node_show = {
    CPARSER_NODE_KEYWORD,
    0,
    "show",
    NULL,
    &cparser_node_configure,
    &cparser_node_show_users
};

cparser_node_t cparser_node_run_script_filename_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_run_script_filename,
    "Run the configuration script",
    NULL,
    NULL
};

cparser_node_t cparser_node_run_script_filename = {
    CPARSER_NODE_STRING,
    0,
    "<STRING:filename>",
    NULL,
    NULL,
    &cparser_node_run_script_filename_eol
};

cparser_node_t cparser_node_run_script = {
    CPARSER_NODE_KEYWORD,
    0,
    "run-script",
    NULL,
    &cparser_node_show,
    &cparser_node_run_script_filename
};

cparser_node_t cparser_node_enable_privileged_mode_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_enable_privileged_mode,
    "Enable privileged mode",
    NULL,
    NULL
};

cparser_node_t cparser_node_enable_privileged_mode = {
    CPARSER_NODE_KEYWORD,
    0,
    "privileged-mode",
    NULL,
    NULL,
    &cparser_node_enable_privileged_mode_eol
};

cparser_node_t cparser_node_enable = {
    CPARSER_NODE_KEYWORD,
    0,
    "enable",
    NULL,
    &cparser_node_run_script,
    &cparser_node_enable_privileged_mode
};

cparser_node_t cparser_node_logout_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_logout,
    "logout from current session",
    NULL,
    NULL
};

cparser_node_t cparser_node_logout = {
    CPARSER_NODE_KEYWORD,
    0,
    "logout",
    NULL,
    &cparser_node_enable,
    &cparser_node_logout_eol
};

cparser_node_t cparser_node_lock_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_lock,
    "Locks the Console",
    NULL,
    NULL
};

cparser_node_t cparser_node_lock = {
    CPARSER_NODE_KEYWORD,
    0,
    "lock",
    NULL,
    &cparser_node_logout,
    &cparser_node_lock_eol
};

cparser_node_t cparser_node_clear_screen_eol = {
    CPARSER_NODE_END,
    0,
    cparser_glue_clear_screen,
    "Clears the screen",
    NULL,
    NULL
};

cparser_node_t cparser_node_clear_screen = {
    CPARSER_NODE_KEYWORD,
    0,
    "screen",
    NULL,
    NULL,
    &cparser_node_clear_screen_eol
};

cparser_node_t cparser_node_clear = {
    CPARSER_NODE_KEYWORD,
    0,
    "clear",
    NULL,
    &cparser_node_lock,
    &cparser_node_clear_screen
};

cparser_node_t cparser_root = {
    CPARSER_NODE_ROOT,
    0,
    NULL,
    "Root node of the parser tree",
    NULL,
    &cparser_node_clear
};

