/*----------------------------------------------------------------------
 * This file is generated by mk_parser.py.
 *----------------------------------------------------------------------*/
#ifndef __CPARSER_TREE_H__
#define __CPARSER_TREE_H__

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

extern cparser_node_t cparser_root;

cparser_result_t cparser_glue_clear_screen (cparser_t *parser);
cparser_result_t cparser_glue_lock (cparser_t *parser);
cparser_result_t cparser_glue_logout (cparser_t *parser);
cparser_result_t cparser_glue_enable_privileged_mode (cparser_t *parser);
cparser_result_t cparser_glue_run_script_filename (cparser_t *parser);
cparser_result_t cparser_glue_system_linuxcommands_args (cparser_t *parser);
cparser_result_t cparser_glue_show_users (cparser_t *parser);
cparser_result_t cparser_glue_show_interface (cparser_t *parser);
cparser_result_t cparser_glue_show_ip_interface (cparser_t *parser);
cparser_result_t cparser_glue_show_ip_route (cparser_t *parser);
cparser_result_t cparser_glue_configure_terminal (cparser_t *parser);
cparser_result_t cparser_glue_config_set_hostname_hostname (cparser_t *parser);
cparser_result_t cparser_glue_config_user_add_username_password_level (cparser_t *parser);
cparser_result_t cparser_glue_config_user_del_username (cparser_t *parser);
cparser_result_t cparser_glue_config_end (cparser_t *parser);
cparser_result_t cparser_glue_config_exit (cparser_t *parser);
cparser_result_t cparser_glue_end (cparser_t *parser);
cparser_result_t cparser_glue_exit (cparser_t *parser);
cparser_result_t cparser_cmd_clear_screen(cparser_context_t *context);
cparser_result_t cparser_cmd_lock(cparser_context_t *context);
cparser_result_t cparser_cmd_logout(cparser_context_t *context);
cparser_result_t cparser_cmd_enable_privileged_mode(cparser_context_t *context);
cparser_result_t cparser_cmd_run_script_filename(cparser_context_t *context,
    char **filename_ptr);
cparser_result_t cparser_cmd_system_linuxcommands_args(cparser_context_t *context,
    char **linuxcommands_ptr,
    char **args_ptr);
cparser_result_t cparser_cmd_show_users(cparser_context_t *context);
cparser_result_t cparser_cmd_show_interface(cparser_context_t *context);
cparser_result_t cparser_cmd_show_ip_interface(cparser_context_t *context);
cparser_result_t cparser_cmd_show_ip_route(cparser_context_t *context);
cparser_result_t cparser_cmd_configure_terminal(cparser_context_t *context);
cparser_result_t cparser_cmd_config_set_hostname_hostname(cparser_context_t *context,
    char **hostname_ptr);
cparser_result_t cparser_cmd_config_user_add_username_password_level(cparser_context_t *context,
    char **username_ptr,
    char **password_ptr,
    int32_t *level_ptr);
cparser_result_t cparser_cmd_config_user_del_username(cparser_context_t *context,
    char **username_ptr);
cparser_result_t cparser_cmd_config_end(cparser_context_t *context);
cparser_result_t cparser_cmd_config_exit(cparser_context_t *context);
cparser_result_t cparser_cmd_end(cparser_context_t *context);
cparser_result_t cparser_cmd_exit(cparser_context_t *context);

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* __CPARSER_TREE_H__ */
